### ISSUE TITLE
AttributeError: module 'markdown' has no attribute 'version'

### ISSUE THREAD

**Issue by neverfind** [psono/psono-server#3]
psono@ubuntu16:/root$ python3 ~/psono-server/psono/manage.py generateserverkeys
Traceback (most recent call last):
  File "/home/psono/psono-server/psono/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.p                                                                                        y", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.p                                                                                        y", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in                                                                                         setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 11                                                                                        2, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 198,                                                                                         in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/psono/psono-server/psono/restapi/models.py", line 14, in <module>
    from .fields import LtreeField
  File "/home/psono/psono-server/psono/restapi/fields.py", line 4, in <module>
    from rest_framework.serializers import UUIDField as InsecureUUIDField
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", l                                                                                        ine 30, in <module>
    from rest_framework.compat import postgres_fields, unicode_to_repr
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/compat.py", line 1                                                                                        61, in <module>
    if markdown.version <= '2.2':
AttributeError: module 'markdown' has no attribute 'version'

**Comment by chickahoona** [comment]
Thanks, I think its related to https://github.com/encode/django-rest-framework/issues/6203 but Ill have to investigate.

**Comment by neverfind** [comment]
Yup let me know if you find a fix i've been trying to get psono working for a while
